import os
import uuid
import io
import requests
from typing import List, Dict, Optional
from supabase import create_client, Client
from dotenv import load_dotenv
from xhtml2pdf import pisa

# Load environment variables
load_dotenv()

# =============================================================================
# 1. CONFIGURATION
# =============================================================================

SUPABASE_URL = os.getenv('SUPABASE_URL')
SUPABASE_SERVICE_KEY = os.getenv('SUPABASE_SERVICE_KEY') or os.getenv('SUPABASE_KEY')
N8N_WEBHOOK_URL = "https://n8n.sitesync.tech/webhook/send-estimate"
N8N_SECRET = os.getenv('N8N_SECRET')
BUCKET_NAME = 'estimates'
LOGO_URL = 'https://eris.co.ke/eris-engineering-logo.svg'

# =============================================================================
# 2. PDF GENERATION (xhtml2pdf)
# =============================================================================

def generate_simple_pdf(client_data: Dict[str, str], estimate_items: List[Dict[str, str]]) -> bytes:
    """
    Generates a PDF estimate using xhtml2pdf (CSS 2.1 compliant).
    
    Args:
        client_data: Dict with 'name', 'email', 'project'.
        estimate_items: List of dicts with 'item', 'description', 'cost'.
        
    Returns:
        bytes: The generated PDF content.
    """
    
    # Calculate Total
    total_cost = 0.0
    rows_html = ""
    
    for item in estimate_items:
        cost_str = str(item.get('cost', '0')).replace(',', '').replace('KES', '').strip()
        try:
            cost_val = float(cost_str)
            total_cost += cost_val
        except ValueError:
            cost_val = 0.0
            
        rows_html += f"""
        <tr>
            <td style="padding: 8px; border-bottom: 1px solid #ddd;">{item.get('item', '')}</td>
            <td style="padding: 8px; border-bottom: 1px solid #ddd;">{item.get('description', '')}</td>
            <td style="padding: 8px; border-bottom: 1px solid #ddd; text-align: right;">{cost_val:,.2f}</td>
        </tr>
        """

    # HTML Template (CSS 2.1 compatible - No Flexbox)
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            @page {{
                size: A4;
                margin: 2cm;
                @frame footer_frame {{
                    -pdf-frame-content: footerContent;
                    bottom: 1cm;
                    margin-left: 2cm;
                    margin-right: 2cm;
                    height: 1cm;
                }}
            }}
            body {{
                font-family: Helvetica, sans-serif;
                font-size: 12px;
                color: #333333;
            }}
            .header-table {{
                width: 100%;
                margin-bottom: 20px;
                border-bottom: 2px solid #eeeeee;
            }}
            .logo {{
                width: 120px;
                height: auto;
            }}
            .title {{
                font-size: 24px;
                font-weight: bold;
                color: #2c3e50;
                text-align: right;
            }}
            .client-box {{
                background-color: #f9f9f9;
                padding: 15px;
                margin-bottom: 20px;
                border: 1px solid #eeeeee;
            }}
            .items-table {{
                width: 100%;
                border-collapse: collapse;
                margin-top: 20px;
            }}
            .items-table th {{
                background-color: #f2f2f2;
                color: #555555;
                font-weight: bold;
                padding: 10px;
                text-align: left;
                border-bottom: 2px solid #dddddd;
            }}
            .total-row td {{
                font-weight: bold;
                font-size: 14px;
                padding-top: 10px;
                border-top: 2px solid #333333;
            }}
            .watermark {{
                position: fixed;
                top: 50%;
                left: 50%;
                transform: rotate(45deg);
                font-size: 80px;
                color: #eeeeee;
                z-index: -1000;
                text-align: center;
                width: 100%;
                opacity: 0.3;
            }}
        </style>
    </head>
    <body>
        <!-- Watermark -->
        <div class="watermark">ROUGH ESTIMATE</div>

        <!-- Header Layout using Table -->
        <table class="header-table">
            <tr>
                <td valign="middle">
                    <img src="{LOGO_URL}" class="logo" />
                </td>
                <td valign="middle" align="right">
                    <div class="title">Construction Estimate</div>
                    <div style="color: #777;">Generated by Fundi Agent</div>
                </td>
            </tr>
        </table>

        <!-- Client Info -->
        <div class="client-box">
            <h3 style="margin-top: 0; color: #555;">Client Details</h3>
            <p>
                <b>Name:</b> {client_data.get('name', 'Valued Client')}<br/>
                <b>Email:</b> {client_data.get('email', 'N/A')}<br/>
                <b>Project:</b> {client_data.get('project', 'Residential Construction')}
            </p>
        </div>

        <!-- Items Table -->
        <table class="items-table">
            <thead>
                <tr>
                    <th width="30%">Item</th>
                    <th width="50%">Description</th>
                    <th width="20%" align="right">Cost (KES)</th>
                </tr>
            </thead>
            <tbody>
                {rows_html}
                <tr class="total-row">
                    <td colspan="2" align="right">Total Estimated Cost:</td>
                    <td align="right">{total_cost:,.2f}</td>
                </tr>
            </tbody>
        </table>

        <!-- Footer (Defined in @page frame) -->
        <div id="footerContent" align="center" style="color: #999; font-size: 10px;">
            This is an AI-generated rough estimate. Actual costs may vary based on site conditions.
            <br/>&copy; 2025 Eris Engineering.
        </div>
    </body>
    </html>
    """

    # Convert HTML to PDF
    print("📄 Generating PDF with xhtml2pdf...")
    pdf_buffer = io.BytesIO()
    pisa_status = pisa.CreatePDF(io.StringIO(html_content), dest=pdf_buffer)
    
    if pisa_status.err:
        print("❌ PDF Generation Error")
        return b""
        
    return pdf_buffer.getvalue()

# =============================================================================
# 3. WORKFLOW ORCHESTRATION
# =============================================================================

def handle_estimate_workflow(user_email: str, user_name: str, pdf_bytes: bytes) -> bool:
    """
    Orchestrates the secure delivery: Upload -> Webhook.
    """
    print(f"🚀 Starting workflow for {user_email}...")

    if not pdf_bytes:
        print("❌ Error: PDF content is empty.")
        return False

    # 1. Initialize Supabase
    if not SUPABASE_URL or not SUPABASE_SERVICE_KEY:
        print("❌ Error: Missing Supabase credentials.")
        return False
        
    try:
        supabase: Client = create_client(SUPABASE_URL, SUPABASE_SERVICE_KEY)
    except Exception as e:
        print(f"❌ Error initializing Supabase: {e}")
        return False

    # 2. Generate Filename
    filename = f"estimate_{uuid.uuid4()}.pdf"

    try:
        # 3. Upload to Supabase
        print(f"📤 Uploading {filename}...")
        supabase.storage.from_(BUCKET_NAME).upload(
            path=filename,
            file=pdf_bytes,
            file_options={"content-type": "application/pdf"}
        )

        # 4. Get Public URL
        public_url = supabase.storage.from_(BUCKET_NAME).get_public_url(filename)
        
        # Handle legacy return type if necessary
        if not isinstance(public_url, str) and hasattr(public_url, 'publicURL'):
             public_url = public_url.publicURL
             
        print(f"✅ Uploaded: {public_url}")

        # 5. Trigger n8n Webhook
        payload = {
            "email": user_email,
            "name": user_name,
            "pdf_url": public_url
        }

        headers = {
            "Content-Type": "application/json",
            "x-n8n-header-auth": N8N_SECRET if N8N_SECRET else ""
        }

        print(f"🔗 Calling Webhook: {N8N_WEBHOOK_URL}")
        response = requests.post(N8N_WEBHOOK_URL, json=payload, headers=headers, timeout=15)

        if response.status_code == 200:
            print("✅ Webhook Success! Estimate sent.")
            return True
        else:
            print(f"❌ Webhook Failed: {response.status_code} - {response.text}")
            return False

    except Exception as e:
        print(f"❌ Workflow Error: {str(e)}")
        return False

# =============================================================================
# 4. MAIN EXECUTION (TEST)
# =============================================================================

if __name__ == "__main__":
    print("🧪 Running Estimate Delivery Test (xhtml2pdf)...")
    
    # Dummy Data
    client = {
        "name": "Jane Doe",
        "email": "jane.test@example.com",
        "project": "3BR Bungalow in Mombasa"
    }
    
    items = [
        {"item": "Preliminaries", "description": "Site clearance and setup", "cost": "50000"},
        {"item": "Substructure", "description": "Foundation works", "cost": "250000"},
        {"item": "Superstructure", "description": "Walling and columns", "cost": "300000"},
        {"item": "Roofing", "description": "Timber truss and sheets", "cost": "180000"}
    ]

    # Run
    pdf_content = generate_simple_pdf(client, items)
    
    if pdf_content:
        handle_estimate_workflow(client["email"], client["name"], pdf_content)
    else:
        print("❌ Failed to generate PDF.")
